# Generated by Django 4.2 on 2023-04-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(choices=[('Y', 'Yellow'), ('R', 'Red')], default='Y', max_length=2, verbose_name='Каточка')),
            ],
        ),
        migrations.CreateModel(
            name='CauseSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Причина пропуска')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_day', models.DateTimeField(blank=True, null=True, verbose_name='Дата и Время игры')),
                ('Goals', models.SmallIntegerField(default=0, verbose_name='Наши голы')),
                ('Opponent_goals', models.SmallIntegerField(default=0, verbose_name='Голы Оппонента')),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('Lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('Patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('Phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Контактный Номер')),
                ('Age', models.SmallIntegerField(verbose_name='Возраст')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активный')),
                ('PlayNumber', models.SmallIntegerField(blank=True, default=-1, null=True, verbose_name='Игровой Номер игрока')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название')),
                ('Start_dt', models.DateField(verbose_name='Начало')),
                ('Stop_dt', models.DateField(blank=True, null=True, verbose_name='Конец')),
                ('IsComplete', models.BooleanField(default=False, verbose_name='Завершен')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_workout', models.DateField(auto_created=True, verbose_name='Дата Тренировки')),
                ('Enable', models.BooleanField(default=True, verbose_name='Состоялась')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attandend', models.BooleanField(default=True, verbose_name='Присутвовал')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.causeskip', verbose_name='Причина Пропуска')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goals', models.SmallIntegerField(verbose_name='Колчество голов')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.game', verbose_name='Игры')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.player', verbose_name='Игрок')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='Opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.opponent', verbose_name='Оппонент'),
        ),
    ]
